services:
  web:
    build: .
    ports:
      - "127.0.0.1:7676:5000"
    environment:
      FLASK_APP: see_the_growth.api.local_web_app:create_app
      SEE_THE_GROWTH_PORT: "5000"
    volumes:
      - ./data:/app/data
